const SET_SHOW_SIDEBAR = "SET_SHOW_SIDEBAR";
const SET_OVERFLOW_NAVBAR = "SET_OVERFLOW_NAVBAR";
const SET_SHOW_INTROVIDEO_MODAL = "SET_SHOW_INTROVIDEO_MODAL";
const SET_SCREEN_WIDTH = "SET_SCREEN_WIDTH";
export {
  SET_SHOW_SIDEBAR,
  SET_OVERFLOW_NAVBAR,
  SET_SHOW_INTROVIDEO_MODAL,
  SET_SCREEN_WIDTH,
};
