export const jobs = [
  {
    id: 1,
    job: {
      id: 1,
      name:  "I will design an outstanding logo",
      reviewCount: 100,
      price: 15,
      sellerId: 1,
      thumbUrl: "https://fiverrnew.cybersoft.edu.vn/images/cv1.jpg",
      longDescription: "\nHi There,\r\n\r\n\r\n\r\nHave You Been Looking for a Brand Logo with Complete Corporate Brand Identity?\r\n\r\n\r\n\r\nHi, I am Talha, a Passionate Professional Graphic Designer designing brand logos & brand Identity for many Years, I have successfully designed brand logos with the complete corporate brand identity for different brands around the world.\r\n\r\n\r\n\r\nI also would love to do demanded designs, Just leave your request, I will respond instantly.",
      serviceId: 2,
      shortDescription:
        "Plus - MOST SELLING!\r\nUS$65\r\n3 logo options + source file in Ai, EPS, SVG, PDF, and PSD\r\n\r\n2 Days Delivery\r\n5 Revisions\r\n3 concepts included\r\nLogo transparency\r\nVector file\r\nPrintable file\r\nSource file",
      rating: 1,
    },
    jobCategoryName: "Graphics & Design",
    jobSubCategoryName: "Logo & Brand Identity",
    serviceName: "Logo Design",
    sellerName: "admin",
    avatar: "http://sc04.alicdn.com/kf/Hc3e61591078043e09dba7808a6be5d21n.jpg",
  },
  {
    id: 2,
    job: {
      id: 2,
      name:  "I will design 3 modern minimalist flat logo designs",
      reviewCount: 19907,
      price: 30,
      sellerId: 1,
      thumbUrl: "https://fiverrnew.cybersoft.edu.vn/images/cv2.jpg",
      longDescription: "\nHi There,\r\n\r\n\r\n\r\nHave You Been Looking for a Brand Logo with Complete Corporate Brand Identity?\r\n\r\n\r\n\r\nHi, I am Talha, a Passionate Professional Graphic Designer designing brand logos & brand Identity for many Years, I have successfully designed brand logos with the complete corporate brand identity for different brands around the world.\r\n\r\n\r\n\r\nI also would love to do demanded designs, Just leave your request, I will respond instantly.",
      serviceId: 2,
      shortDescription:
        "US$30\r\nSave up to 15% with Subscribe to Save\r\nSTANDARD Package - Recommended 5 ULTRA HQ logos + Free Revisions + Vector Source files(Ai, EPS, PDF) for final design\r\n\r\n2 Days Delivery\r\nUnlimited Revisions",
      rating: 2,
    },
    jobCategoryName: "Graphics & Design",
    jobSubCategoryName: "Logo & Brand Identity",
    serviceName: "Logo Design",
    sellerName: "admin",
    avatar: "http://sc04.alicdn.com/kf/Hc3e61591078043e09dba7808a6be5d21n.jpg",
  },
  {
    id: 3,
    job: {
      id: 3,
      name: 
        "I will design minimal logo with complete corporate brand identity",
      reviewCount: 66,
      price: 10,
      sellerId: 1,
      thumbUrl: "https://fiverrnew.cybersoft.edu.vn/images/cv3.jpg",
      longDescription: "\nHi There,\r\n\r\n\r\n\r\nHave You Been Looking for a Brand Logo with Complete Corporate Brand Identity?\r\n\r\n\r\n\r\nHi, I am Talha, a Passionate Professional Graphic Designer designing brand logos & brand Identity for many Years, I have successfully designed brand logos with the complete corporate brand identity for different brands around the world.\r\n\r\n\r\n\r\nI also would love to do demanded designs, Just leave your request, I will respond instantly.",
      serviceId: 3,
      shortDescription:
        "US$10\r\nSave up to 20% with Subscribe to Save\r\nBASIC CORPORATE BRAND IDENTITY Business Card + Letterhead + Compliment Design\r\n\r\n2 Days Delivery\r\nUnlimited Revisions\r\nIncludes logo design\r\nLogo usage guidelines\r\nColor palette\r\nTypography guidelines",
      rating: 4,
    },
    jobCategoryName: "Graphics & Design",
    jobSubCategoryName: "Logo & Brand Identity",
    serviceName: "Brand Style Guides",
    sellerName: "admin",
    avatar: "http://sc04.alicdn.com/kf/Hc3e61591078043e09dba7808a6be5d21n.jpg",
  },
  {
    id: 4,
    job: {
      id: 4,
      name:  "I will do modern logo design with premium brand identity",
      reviewCount: 422,
      price: 35,
      sellerId: 1,
      thumbUrl: "https://fiverrnew.cybersoft.edu.vn/images/cv4.jpg",
      longDescription: "\nHi There,\r\n\r\n\r\n\r\nHave You Been Looking for a Brand Logo with Complete Corporate Brand Identity?\r\n\r\n\r\n\r\nHi, I am Talha, a Passionate Professional Graphic Designer designing brand logos & brand Identity for many Years, I have successfully designed brand logos with the complete corporate brand identity for different brands around the world.\r\n\r\n\r\n\r\nI also would love to do demanded designs, Just leave your request, I will respond instantly.",
      serviceId: 3,
      shortDescription:
        "US$10\r\nSave up to 20% with Subscribe to Save\r\nBASIC CORPORATE BRAND IDENTITY Business Card + Letterhead + Compliment Design\r\n\r\n2 Days Delivery\r\nUnlimited Revisions\r\nIncludes logo design\r\nLogo usage guidelines\r\nColor palette\r\nTypography guidelines",
      rating: 3,
    },
    jobCategoryName: "Graphics & Design",
    jobSubCategoryName: "Logo & Brand Identity",
    serviceName: "Brand Style Guides",
    sellerName: "admin",
    avatar: "http://sc04.alicdn.com/kf/Hc3e61591078043e09dba7808a6be5d21n.jpg",
  },
  {
    id: 6,
    job: {
      id: 6,
      name:  "I will design professional social media post",
      reviewCount: 55,
      price: 30,
      sellerId: 1,
      thumbUrl: "https://fiverrnew.cybersoft.edu.vn/images/cv6.jpg",
      longDescription: "\r\nWelcome to our Social Media Posts Design.\r\n\r\nWe understand the client's needs and assist through the whole process with professionalism.\r\n\r\nWe are experienced in creating social media graphic content for clients all over the world, for business, products, and personal brands.\r\n\r\nWe can assist you to improve the appearance of your social media presence.",
      serviceId: 5,
      shortDescription:
        "US$30\r\nSave up to 10% with Subscribe to Save\r\nBASIC 3 unique social media posts with the most attractive content that will transform your business.\r\n\r\n2 Days Delivery\r\n3 social posts created",
      rating: 2,
    },
    jobCategoryName: "Writing & Translation",
    jobSubCategoryName: "Content Writing & Editing",
    serviceName: "Website Design",
    sellerName: "admin",
    avatar: "http://sc04.alicdn.com/kf/Hc3e61591078043e09dba7808a6be5d21n.jpg",
  },
];