export const columns = [
  {
    title: "Categories",
    list: [
      "Graphics & Design",
      "Digital Marketing",
      "Writing & Translation",
      "Video & Animation",
      "Music & Audio",
      "Programming & Tech",
      "Data",
      "Business",
      "Lifestyle",
      "Sitemap",
    ],
  },
  {
    title: "About",
    list: [
      "Careers",
      "Press & News",
      "Partnerships",
      "Privacy Policy",
      "Terms of Service",
      "Intellectual Property Claims",
      "Investor Relations",
    ],
  },
  {
    title: "Support",
    list: [
      "Help & Support",
      "Trust & Safety",
      "Selling on Fiverr",
      "Buying on Fiverr",
    ],
  },
  {
    title: "Community",
    list: [
      "Events",
      "Blog",
      "Forum",
      "Community Standards",
      "Podcast",
      "Affiliates",
      "Invite a Friend",
      "Become a Seller",
    ],
  },
  {
    title: "More From Fiverr",
    list: [
      "Fiverr Business",
      "Fiverr Pro",
      "Fiverr Studios",
      "Fiverr Logo Maker",
      "Fiverr Guides",
      "Get Inspired",
      "Fiverr Select",
      "ClearVoice",
      "Content Marketing",
      { main: "Fiverr Workspace", sub: "Invoice Software" },
      { main: "Learn", sub: "Online Courses" },
      "Working Not Working",
    ],
  },
];
